### ISSUE TITLE
Use +/- to change values

### ISSUE THREAD

**Issue by tjvr** [cambridge-alpha-team/unvisual-frontend#10]
the way changing a parameter value currently works is unintuitive:
1. We press `→` to access the list of options.
   
   Going "inside" a parameter value to access its options doesn't make any
   sense.
2. We press `↑`/`↓` to change value. This is ok.
3. The option is not saved immediately, so if we press `↩` to execute the
   code, we won't notice any change.
4. It's natural to press `←` after choosing the desired value, since we
   want to go back out, up the tree. 
   
   But instead, this _cancels_ the change! This is unintuitive and
   frustrating.
5. We press `→` to confirm the change. This doesn't make any sense!
   - `→` is mainly used to go "inside" a node. You can't go inside a
     number.
   - after setting the value, it moves you _up_ the tree, not down!

I propose using dedicated keys for changing values, for example `+`/`-`.
(Yes, I realise those keys currently have a different purpose; we can pick
something else for those actions.)

We established in the UX testing that nesting is bad. Using dedicated
keys has the following advantages:
- change takes effect instantly; no need to confirm choice
- can't accidentally "cancel" change
- no confusing spatial relationships

**Comment by isaac-dunn** [comment]
I couldn't agree more with your evaluation of the problem - that's very nicely put into words. I'm not completely certain your proposed solution is the best possible, though. Perhaps we could just make it that up and down were used to change the parameter value as before, but instead of pressing right, you just pressed left to save the new value and go back?

**Comment by tjvr** [comment]
> we could just make it that up and down were used to change the parameter value as before, but instead of pressing right, you just pressed left to save the new value and go back?

That would still be a marked improvement—assuming the values are saved _immediately_ instead of after pressing `←`.

Adding a confirmation step is unintuitive and unnecessary. We already have the "run code" action to send the updated code to Sonic Pi. And if there's no way to _cancel_ changing the value, then there's no advantage to not updating the value instantly. One user changed the value and pressed `↩` before confirming the value by pressing `→`, and was surprised when the sound didn't change. They expected it to have updated immediately. We should do what the user expects.

So the values must be saved immediately.

I'm less concerned about whether you have to go "into" a value to change it, but I do still prefer `+`/`-`.

**Comment by tjvr** [comment]
Maybe we should consider how we could add expressions—such as choosing a note at random from a scale—and see how that informs the design of values?

**Comment by isaac-dunn** [comment]
That's a good idea - we need to decide how much freedom we're going to give the users. At the moment, we're restricting them to playing one note at a time. Presumably we're going to add `play_chord` etc., but Sonic Pi supports playing from scales, and possibly also from arbitrary collections of notes (I can't remember sorry).

Clearly more advanced users would be grateful for extra freedom, but it could add extra complexity which is confusing for younger children.

**Comment by RusticFlare** [comment]
We are now updating the values live using the 'up' and 'down' keys. I don't think we should use the +/- keys because the 'up' and 'down' keys work fine. Therefore we can close this issue.

**Comment by isaac-dunn** [comment]
What do you mean, "updating the values live"?

**Comment by RusticFlare** [comment]
There is no need to press confirm, and the values are set as you cycle through.

**Comment by isaac-dunn** [comment]
Okay, that's what I suggested above. Tim said he'd still prefer the +/-, I think.
