### ISSUE TITLE
Announce start/end of list

### ISSUE THREAD

**Issue by tjvr** [cambridge-alpha-team/unvisual-frontend#11]
eg. alert when we reach the min/max value for a ValueNode.

Though this does apply to _all_ lists too (the list of loops, for example).

One user thought the "down" key was broken.

One user commented "when you get to the end, it repeats itself!"

**Comment by tjvr** [comment]
Above, I wrote:

> this does apply to all lists too (the list of loops, for example).

This is still an issue for lists: for example, when the last loop is focused, there's no feedback when pressing `↓`.

**Comment by RusticFlare** [comment]
Fixed
