### ISSUE TITLE
Improve "add" action

### ISSUE THREAD

**Issue by tjvr** [cambridge-alpha-team/unvisual-frontend#13]
The "add" mode has several usability issues. It's not clear that there is a choice of options, and invalid options can be selected.
- [x] doesn't announce the number of options
- [x] doesn't announce its first option (see #12).
- [ ] doesn't allow typing: eg. "syn" should select synth.
- [x] isn't context-sensitive: allows adding inappropriate node types.

The last problem is the biggest. Only allowing the user to add nodes which are valid in that context will avoid some really nasty problems, and will reduce the number of the options for the user to choose from and therefore make the interface quicker to use.

**Comment by isaac-dunn** [comment]
All good points. Should these be split into separate issues though? Some of these are much higher priority than others, and it would make it clearer what still needs to be done.

**Comment by RusticFlare** [comment]
I don't think that we are going to implement the predictive typing of "syn"->"synth" so we should close this issue
