### ISSUE TITLE
Undo

### ISSUE THREAD

**Issue by tjvr** [cambridge-alpha-team/unvisual-frontend#14]
Instead of confirming things, we should have a reliable undo system.

The partially-sighted kid who didn't use the screen reader had the font size set very large. This meant that the following message completely filled the screen:

> "Are you sure you want to delete this bit of code? Press right to confirm or left to cancel."

It would be better to perform the action without confirmation, and then provide the option to undo. We could even announce "Press ‹key› to undo" after deleting, to make this clear.

**Comment by Psyclone150** [comment]
How many actions should be remembered? Just the previous one or a whole series of actions?

**Comment by tjvr** [comment]
No reason not to have unlimited undo.

**Comment by Psyclone150** [comment]
I'm working on this.
