### ISSUE TITLE
Changing values too quickly causes silence

### ISSUE THREAD

**Issue by tjvr** [cambridge-alpha-team/unvisual-frontend#15]
If you hold down the key while changing values, there's no feedback from the screen reader.

Here's how we can fix this:
- this happens because we're calling `say()` very quickly.
- we could fix this by only `say()`-ing things if enough time has elapsed since the last `say()`.
- however, doing this naïvely will stop the screenreader from saying anything at all if we navigate the tree too quickly—which is not what we want!
- so we need to special-case the `say()` call for change-value readouts, and have a very small timeout for those (eg. 500 ms).

**Comment by Psyclone150** [comment]
This seems to work, but after discussing it with Lulu we decided to take a slightly different approach to scrolling through lists. Instead of scrolling by holding the button down, we thought it would be better to trigger "say" when the button is released (as opposed to pressed), but a double-release in quick succession jumps up or down by up to 10 nodes in the list and a triple-release jumps straight to the first or last item.

**Comment by isaac-dunn** [comment]
Hmm I'm not sure about that behaviour. If a user presses down two times, they expect to move down two items, not eleven! Unless you are fully aware that it behaves like this, I suspect it could be extremely confusing.

**Comment by LauraneS** [comment]
If they know that pressing it _quickly_ twice or three times changes the way it goes up or down though? It is essentially as if they'd pressed the key down for a bit because they wanted to go right up or down

**Comment by LauraneS** [comment]
I do understand it is not the best solution, but I don't think it is possible to have the screenreader read out all the values if someone is holdingthe button down. I also don't think it is actually necessary to be honest. If a user is pressing the button down, and the screen reader periodically outputs a value, by the time the screen reader is done saying "a hundred and twenty seven", the number displayed on the screen will already be much higher (or lower), so it is equally confusing...

**Comment by Psyclone150** [comment]
If we're still undecided about the best way to run through long lists quickly, shall I merge this branch now so that we have made at least some progress in addressing this issue?

**Comment by LauraneS** [comment]
Maybe merging it is not necessary? The screenreader works fine -except for that little detail - so I reckon we can use it as it is for now?

**Comment by RusticFlare** [comment]
I think that the set up we have works well. Reading should take place on a key release.

**Comment by RusticFlare** [comment]
Closed because of 'wontfix' label
