### ISSUE TITLE
Keyboard focus may get lost

### ISSUE THREAD

**Issue by tjvr** [cambridge-alpha-team/unvisual-frontend#16]
Sometimes, the screen reader steals focus away from our webapp. This seems to happen when pressing any of the arrow keys. We had to fix this several times during the usability test, by pressing the magic shortcut `⇧⌃⌥↓` (which moves Voiceover's focus into the web page).

To fix this: make sure you `return false;` from every event handler.

**Comment by RusticFlare** [comment]
I've put in a pull request to fix this #24
