### ISSUE TITLE
Announce range of choices

### ISSUE THREAD

**Issue by tjvr** [cambridge-alpha-team/unvisual-frontend#17]
Theo suggested announcing the range of choices.

For example, expanding "play 60" would indicate the minimum and maximum values allowed.

Relevant to #10

**Comment by isaac-dunn** [comment]
Actually, what's even the point of the minimum and the maximum? Kids love doing stuff like "I wonder what's the lowest we can get it to go" or "I wonder whats the fastest we can get it to play", and the restrictions seem pretty artificial and pointless to me.

**Comment by tjvr** [comment]
Some restrictions _are_ real: for example, neither tempo or amplitude can be negative.

It's nice to experiment, but extreme values can cause unexpected results: note 40 is too low to hear, and even our current default of 60 is pretty hard to hear without earphones. This matters because the user will struggle to work out what's wrong (have they used the "play" command correctly?), which may impede their learning or make them frustrated.

**Comment by isaac-dunn** [comment]
You're right, some restrictions are necessary.

However, I would argue that a limit of 40 is too high, not too low! Although it isn't audible without headphones, it certainly is with them (or with the quality of equipment that'd be used in a live coding performance), which is what people will be using in a classroom situation. The user I was working with and I had a lot of fun at the meeting experimenting with low grumbling sounds, and lower notes would definitely have been appreciated.

That particular example isn't super important, but for another example the tempo constraints at the moment seem to be very artificially constrained.

**Comment by tjvr** [comment]
We spent a lot of time on the tempo constraints: we chose 60–180 because it encompasses almost all styles of music, with 120 as the default in the middle of the range, which is the tempo for almost all pop music.

Note that the range of tempo affects other things too, such as the step for the sleep statement. If the tempo range is unrestricted, a usable step size is harder to design.

**Comment by isaac-dunn** [comment]
I agree that 60 to 180 encompasses most songs, but I don't see what we'd lose by allowing users to pick more extreme tempos?

**Comment by tjvr** [comment]
Also, the range is (presumably) used for the Cubelets: I assumed we'd map 0 to the minimum and 255 to the maximum. Having a sensible range matters for that, at least.

**Comment by isaac-dunn** [comment]
If that's the case then that's definitely justification for it, else in my opinion we should relax the restrictions.

**Comment by LauraneS** [comment]
There is a PR to fix this #34

**Comment by RusticFlare** [comment]
Fixed in #34
