### ISSUE TITLE
Increase step size for some options

### ISSUE THREAD

**Issue by tjvr** [cambridge-alpha-team/unvisual-frontend#18]
We might consider adjusting the step size for the tempo parameter, or some of the other value nodes.

Adjusting in 1-bpm increments is very slow.

**Comment by RusticFlare** [comment]
proposed step size
sleep - 0.125
tempo - 5
note - 1
amp - 0.1
release - 0.1

**Comment by isaac-dunn** [comment]
Those all sound okay to me. Are we going to present the sleep lengths as decimals or as fractions? (See #8)

**Comment by RusticFlare** [comment]
Decimal is how it will be represented in code

**Comment by isaac-dunn** [comment]
Of course, is that relevant? I thought we're moving away from using our tree structure language as a direct representation of Sonic Pi code (see Tim's comments at the end of his initial post in #21).

**Comment by RusticFlare** [comment]
These can now be changed very simply.
