### ISSUE TITLE
Unclear names

### ISSUE THREAD

**Issue by tjvr** [cambridge-alpha-team/unvisual-frontend#19]
- “What is ‘amp’?”
- “What is ‘fm’?”
- “What does loop mean?”
  
  “I only realised what ‘loop’ meant when I played it and heard it repeat itself...”

**Comment by isaac-dunn** [comment]
Also "fx" and "synth" are not at all obvious.

**Comment by RusticFlare** [comment]
This needs sorting

**Comment by isaac-dunn** [comment]
I'm happy to attempt to fix this.

**Comment by RusticFlare** [comment]
great
