### ISSUE TITLE
Visual feedback

### ISSUE THREAD

**Issue by tjvr** [cambridge-alpha-team/unvisual-frontend#20]
Currently, our program gives poor visual feedback.

The Ruby code is incomprehensible: I believe none of our users even looked at it.

The partially-sighted user didn't use the screen reader at all; we simply increased the font size until they could read the spoken text off the screen. Good visual feedback is also important for the teacher helping the child.

I think we should remove the Ruby code, and instead display on-screen the _exact_ same menu system as the one they're navigating. At a minimum, it should display this tree and highlight their current position in it.

**Comment by isaac-dunn** [comment]
I agree. I think it could be useful to think of creating these tree structures as being a programming language in itself, albeit very closely related to and implemented in Sonic Pi.

**Comment by isaac-dunn** [comment]
Also, it would make me happy if you referred to Sonic Pi code as that, rather than Ruby code :P

**Comment by LauraneS** [comment]
I understand your point but I think there should at least be the option to switch between actual Sonic Pi code and the tree. Allowing for code inspection is a requirement in the brief. And the users we had on Friday were quite young, and were just exploring without having been taught anything about sonic Pi beforehand. Maybe after a few sessions they'd actually want to work with the code

**Comment by isaac-dunn** [comment]
That's a good point. If we're treating our system as its own language, separate from Sonic Pi, then viewing the Sonic Pi code that we generate wouldn't be a brief requirement any more, but I do agree that it could be nice.

**Comment by tjvr** [comment]
> Allowing for code inspection is a requirement in the brief.

The brief does not require inspecting _Sonic Pi_ code. Our menu system is still a programming language.

**Comment by RusticFlare** [comment]
I'm working on a system that places a box around the selected code.

**Comment by RusticFlare** [comment]
We are now sticking with boxed Sonic Pi code
