### ISSUE TITLE
Redesign menu structure

### ISSUE THREAD

**Issue by tjvr** [cambridge-alpha-team/unvisual-frontend#21]
Our user testing showed the following:
- keeping track of where we are in the tree is hard.
- nesting is a Bad Thing, and makes getting lost even easier.

So it's important that the menu system is **simple**, and that we have as **few levels** of nesting as possible.

In our current design, there is a direct mapping between the structure of the menu system and the Sonic Pi code. I believe we should divorce the two.

In particular, the way synths/effects are handled is very difficult to manage. In Ruby, they are _nested_ control structures:

``` ruby
live_loop :foo do
  with_fx :ixi_techno do
    with_fx :reverb, amp: 3, room: 0.8, damp: 0.5 do
      with_fx :distortion do
        sample :loop_amen
        sleep sample_duration :loop_amen
      end
    end
  end
end
```

Adding nested control structures such as `with_fx` to the tree is confusing:
- It's not clear where they will be added.
- It's not clear where the user will end up (discussed in #6).
- There's no way to add them **around** a set of notes, nor is it clear how we could facilitate this.
- There's no way to **rearrange** them—eg. if above we wanted the `reverb` to come before the `distortion`, which would produce a different musical effect—and again, this would be non-obvious to design and confusing to use.
- They **increase nesting**—to an unbounded number of levels.

The thing is, adding an effect _around_ a set of statements—usually, the entire body of the loop—is the most common thing to want to do!

I propose that these control structures—`use_synth`, `with_fx`—should _not_ be nested. Instead, since lists are much easier to manage than nesting, we should have a **list of effects**. (Probably, this should be separate from the main body of the loop: maybe have two lists, one with effects and one with statements? Either way, removing nested control structures is important.)

I believe doing this will also allow us greater flexibility when adding support for cubelets. For example, to change parameters on a note while it's playing—which we certainly want—you need to generate extra pieces of Sonic Pi code that run `control` instructions several times a second to update the synth parameter. For example (taken from the demo in London):

``` ruby
live_loop :bar do
  use_synth :prophet
  scale = scale(:C, :minor_pentatonic)
  note = scale.choose
  s = play note, amp: test / 255.0, release: 3
  10.times do
    if dist != 0 then
      control s, note: (dist / 5) + 64
    end
    control s, cutoff: knob * 70 / 255.0 + 50
    sleep 0.1
  end
end
```

I believe making the menu system different and simpler from Sonic Pi code will make things like generating `control` instructions easier to implement.

Our menu system is already different from Sonic Pi code: the text on the nodes is not exactly the same, for example. And it's already clear that we need to change the names further, since the ones in Sonic Pi are confusing (see #19). We're abstracting away names, and I'd argue we need to abstract away the structure as well.

Our tree structure should be its own language, distinct from and simpler than Sonic Pi.

---

> Relevant to: #20, #13

**Comment by isaac-dunn** [comment]
I definitely agree. One question which isn't super important but is vaguely relevant: is it true that putting reverb and distortion in different orders in Sonic Pi produces different aural effects?

**Comment by tjvr** [comment]
> is it true that putting reverb and distortion in different orders in Sonic Pi produces different aural effects?

Absolutely true. It may be hard to discern for that specific example (depending on how musical you are? :p), but as a general principle, the order of the effects chain is very important.

**Comment by isaac-dunn** [comment]
Haha I'll take your word for it, I haven't tried it.

**Comment by isaac-dunn** [comment]
How will we switch between the list of instructions and the list of fx etc. then, assign another key?

**Comment by tjvr** [comment]
I don't think we should bind a key.

Add another level, maybe?
- loop 1 → effects list→reverb…
- loop 1 → program code → sleep 0.5…

Or we could try showing them all in a single list? Which might be nice. But that could be confusing.

This is the kind of thing we could easily A/B test on unsuspecting passers-by.

**Comment by isaac-dunn** [comment]
I know we have agreed that extra tree levels is bad, but think that putting an extra layer here will actually only make things clearer - if you have to choose between the effects and the code, you know what the next list that you're looking at is.

**Comment by RusticFlare** [comment]
I think we are stuck with the system we have

**Comment by RusticFlare** [comment]
Closed because of 'wontfix' label
