### ISSUE TITLE
Implement cubelets support

### ISSUE THREAD

**Issue by RusticFlare** [cambridge-alpha-team/unvisual-frontend#37]
I suggest, having getCubeletValue(cubeletNo, default, min, max, stepSize) and return the cubelet value that scales between the min and max values. It would also be nice if this reset the default to avoid jumps in the sound.

**Comment by tjvr** [comment]
@KoviRobi Does the backend send OSC messages on Cubelet values yet?

**Comment by KoviRobi** [comment]
Yes, look at backend `node-cubelets-server` branch. I will work on it some more later today

**Comment by tjvr** [comment]
How is this supposed to work?

**Comment by KoviRobi** [comment]
I run

```
java -jar target/nativeServer-1.0-SNAPSHOT-jar-with-dependencies.jar ../../../unvisual-frontend ./run-test.sh
```

where test.sh contains

```
#!/bin/sh
VAL=0
while true; do
  cat <<EOF # | nc localhost 8080
{ "95934": null, "96031": ${VAL},  "96147": 0, "96302": null }
EOF
  VAL=$(((${VAL}+1)%256))
  sleep 1s
  # To test watchdog
  if [ "$VAL" -eq 5 ]; then
    VAL=0
  fi
done
```

If you mean how it works behind the scenes, it starts a watchdog thread, which starts an OscExecCubeletsConnection thread, which overrides the handleMessage method of CubeletsConnection, which gets called when the cubelets get updated. Then new values get formatted and sent across the Osc connection.

**Comment by tjvr** [comment]
(Not that it matters now, but: I meant "how does the user interact with this feature".)

**Comment by RusticFlare** [comment]
How is this coming along?

**Comment by KoviRobi** [comment]
Backend works (I think frontend works too)

**Comment by KoviRobi** [comment]
In the demo it seemed to work, can I close it?

**Comment by KoviRobi** [comment]
Actually, in the demo, using the same cubelet value for the sleep as the one for the play did not work, so re-opening this.

**Comment by tjvr** [comment]
I made a separate issue: #73.
