### ISSUE TITLE
Deletions can leave invalid code

### ISSUE THREAD

**Issue by isaac-dunn** [cambridge-alpha-team/unvisual-frontend#41]
It is currently possible to delete, for example, the `note` characteristic of a `play`, so that `play note: 60, amp: 1, release: 1` becomes `play amp: 1, release: 1`. Clearly, this isn't going to be accepted by Sonic Pi.

I would argue that this is relatively easy to do, for example if the user was trying to delete the entire `play` statement, and it might lead to confusion as to why suddenly nothing works.

**Do we want to allow arbitrary deletions of nodes, or only those that leave valid syntax behind?**

**Comment by RusticFlare** [comment]
This is an error. Because we currently cannot add these values they should not be deletable.

**Comment by RusticFlare** [comment]
Please check that PR #42 fixes this.
