### ISSUE TITLE
Stop nesting of live loops

### ISSUE THREAD

**Issue by isaac-dunn** [cambridge-alpha-team/unvisual-frontend#43]
Although this produces technically valid code, it is not something that anyone would ever want to do. Having it at the top of the list of things to be added when you are within a loop is therefore misleading at best.

**Comment by RusticFlare** [comment]
I agree. Rearranging the list is a quick fix, otherwise it would require more work to have different modes for adding code in different places.

**Comment by tjvr** [comment]
@RusticFlare:

> it would require more work to have different modes for adding code in different places.

Wasn't this mentioned way back in #13?

> The "add" mode has several usability issues.
> […]
> - [x] isn't context-sensitive: allows adding inappropriate node types.

**Comment by RusticFlare** [comment]
It now doesn't allow code addition that breaks the code.

**Comment by LauraneS** [comment]
@blob8108 This has been fixed - code addition and deletion is now context sensitive (#26, #42)

Agreed though - just when I was testing #38, I kept adding loops by pressing the wrong key, instead of adding fx. 

What do people think of having the following order: play, sleep, loop, fx, synth, sample?

**Comment by Psyclone150** [comment]
@LauraneS That order seems reasonable. I've also had problems with accidentally adding loops.
Would there be any issues with removing the option to add a loop if you're already in a loop?

**Comment by LauraneS** [comment]
Why would you want to remove that option? It is valid in Sonic Pi isn't it?

**Comment by tjvr** [comment]
As Isaac said:

> it is not something that anyone would ever want to do.

Nesting a live loop inside another live loop may provide valid Sonic Pi code, but it is not ever useful or desirable, and it can produce unexpected behaviour.

Additionally, as I explained on #13:

> Only allowing the user to add nodes which are valid in that context will avoid some really nasty problems, and will **reduce the number of the options for the user to choose from** and therefore make the interface quicker to use.

**Comment by LauraneS** [comment]
Are we preventing nesting of loops then?

**Comment by LauraneS** [comment]
PR #58 should prevent loop nesting
