### ISSUE TITLE
Don't read parameter name while changing it

### ISSUE THREAD

**Issue by tjvr** [cambridge-alpha-team/unvisual-frontend#48]
We fixed #17, so now expanding a parameter explains what it is: for example, pressing `→` to expand a note announces “Choose a value between 40 and 100 for your note: 60”. The precise wording may need tweaking, but the principle is all well and good.

However, we also now announce the name of the parameter _while_ changing it. For example, pressing `↑` will announce “note set to 61”. This is bad, because you can't quickly scan through a range of values. You have to wait for the screen reader to read the "X set to" part every time. (Incidentally, this is also why the fix I suggested for #15 doesn't work.)

Reminding the user what they're changing is not helpful here: they had a nice explanation when they expanded the node, and since they're focused on their current task—setting its value—keeping the parameter in mind is not difficult.

I think we should remove the "X set to" part, and revert to only announcing the value, as we were before.

**Comment by isaac-dunn** [comment]
I agree.

**Comment by LauraneS** [comment]
> (Incidentally, this is also why the fix I suggested for #15 doesn't work.)

I don't think this is why because #17 was fixed after Lara tried to fix #15. 

I will remove the "X set to" part though, I see your point.
