### ISSUE TITLE
Unnecessary tree level under sample node

### ISSUE THREAD

**Issue by isaac-dunn** [cambridge-alpha-team/unvisual-frontend#49]
At the moment, sample nodes have only one attribute: the sample name. Either we should add extra options to the sample node (rate? if we don't want to let them control the rate then maybe we could let them reverse the sample?), or we should remove the extra useless level of the tree (sample -> **sample name** -> {editing sample name}).

**Comment by isaac-dunn** [comment]
Same for synth nodes, actually.

**Comment by RusticFlare** [comment]
The branch `removing-needless-levels` fixes this by removing the option for children on both synth and sample nodes. I think this works fine but I'd like a few opinions.
