### ISSUE TITLE
Cannot add or delete anymore / no more "run" shortcut?

### ISSUE THREAD

**Issue by LauraneS** [cambridge-alpha-team/unvisual-frontend#57]
@blob8108 
Why did we remove cmd+A, cmd+D as shortcuts? I cant test anything anymore, because plus and minus have no action from my keyboard. 

& why have we removed the "run" shortcut?

**Comment by tjvr** [comment]
`+`, `-` work for me. (`+` does require shift, but it works.)

To run, press enter.

**Comment by LauraneS** [comment]
Doesn't work for me :disappointed: 

(I add the shortcuts back in so I can test, its fine)

**Comment by tjvr** [comment]
Try changing your keyboard layout?

**Comment by LauraneS** [comment]
I already have
