### ISSUE TITLE
Remove confirmation step from delete

### ISSUE THREAD

**Issue by tjvr** [cambridge-alpha-team/unvisual-frontend#66]
It would be more intuitive to press `-` a second time to confirm deleting.

**Comment by RusticFlare** [comment]
Do we need to confirm if we have undo?

**Comment by tjvr** [comment]
Good point. As I said in #14:

> It would be better to perform the action without confirmation, and then provide the option to undo. We could even announce “Press ‹key› to undo” after deleting, to make this clear.

**Comment by LauraneS** [comment]
Are we deleting the confirmation step then? Am happy taking care of that issue

**Comment by RusticFlare** [comment]
Yes, do as Tim said.

**Comment by LauraneS** [comment]
PR #88
