### ISSUE TITLE
Sleep node value bug

### ISSUE THREAD

**Issue by tjvr** [cambridge-alpha-team/unvisual-frontend#67]
When setting the value on a sleep node.

When you press the left arrow `←` to go out of the node, its value jumps by `0.125`.

**Comment by KoviRobi** [comment]
Could this be related to the vim h key binding conflicting with the numpad?

**Comment by RusticFlare** [comment]
I can't replicate this.

**Comment by isaac-dunn** [comment]
I also can't reproduce this.

**Comment by RusticFlare** [comment]
As mentioned by Rob this happens because `h` acts as a `^` then `<`

**Comment by tjvr** [comment]
Cool. Should be fixed by #87.
