### ISSUE TITLE
More information at list level of what existing instructions are

### ISSUE THREAD

**Issue by isaac-dunn** [cambridge-alpha-team/unvisual-frontend#7]
I think it would be very useful to have it say "play 50", "sleep 1.5" or whatever, instead of just "play", "sleep", when you're looking at the list of instructions in one loop.

**Comment by tjvr** [comment]
It does...

**Comment by isaac-dunn** [comment]
Has this been changed since the meeting? I'm sure that at the meeting, when looking through the list of instructions in one loop, it just read out "play" rather than "play 60" or whatever.

**Comment by RusticFlare** [comment]
this is fixed
