### ISSUE TITLE
Deleting an empty fx causes crash

### ISSUE THREAD

**Issue by RusticFlare** [cambridge-alpha-team/unvisual-frontend#70]
If you have an empty `fx` and you try to delete it by pressing `-` then `->` the frontend breaks by nothing happening on key presses.

**Comment by KoviRobi** [comment]
Error according to Chromium:
`Uncaught TypeError: Cannot read property 'readFull' of undefined in main.js:181`

In case you did not already know about this:
https://developer.chrome.com/devtools/docs/javascript-debugging#pause-on-exceptions
