### ISSUE TITLE
You cannot delete Synths or Samples

### ISSUE THREAD

**Issue by RusticFlare** [cambridge-alpha-team/unvisual-frontend#71]

**Comment by LauraneS** [comment]
Am happy with "lets you delete sample and synth" part, but if I cannot delete an empty fx; in my particular example, it is inside a loop, and there is nothing else in that loop. If there is another statement in the loop it lets me delete it though. 
Actually, we can never delete a node from a loop if it is the only one in that loop. Is that something we decided? or a bug?

**Comment by RusticFlare** [comment]
That was decided, an empty loop may as well not exist.

**Comment by tjvr** [comment]
> Actually, we can never delete a node from a loop if it is the only one in that loop.

@RusticFlare: it still makes sense to delete the last thing in a loop, since you might want to delete it and replace it with something else.

**Comment by LauraneS** [comment]
That is my opinion as well. 

Sorry if this was already discussed …

**Comment by RusticFlare** [comment]
This would require 3 different adding code modes to fix, one for below current position, one for above, one for inside.

**Comment by RusticFlare** [comment]
A fix for loops is now issue #76
