### ISSUE TITLE
Cubelets can't control `sleep`

### ISSUE THREAD

**Issue by tjvr** [cambridge-alpha-team/unvisual-frontend#73]
In the demo, binding the cubelets to a `sleep` node didn't work.

I'm guessing the way we're generating code for sleep is wrong.

**Comment by RusticFlare** [comment]
Can you please try and reproduce the bug. I think the syntax is right.

**Comment by isaac-dunn** [comment]
In particular, we tried to bind a cubelet to a `play` and simultaneously the following `sleep`. Perhaps this had something to do with it? It worked for the `play`, but not the `sleep`.

**Comment by tjvr** [comment]
I think this is fine now.
