### ISSUE TITLE
Step size for "sleep"

### ISSUE THREAD

**Issue by isaac-dunn** [cambridge-alpha-team/unvisual-frontend#8]
At the moment you can only do sleeps in multiples of 0.5. Do we want a way to have more general sleep lengths (e.g. the length of a given sample, or any decimal number), or is the current simplicity better?

**Comment by tjvr** [comment]
Musically speaking, you want _fractions_: `1/2`, `1/4`, `3/4`, and so on. A step size of an eighth should be small enough.

Also: `sleep 0` should be disallowed, since it's equivalent to no sleep statement.

> the length of a given sample

I think we should automatically sync samples with the current tempo, eg:

`sample :loop_amen` →

``` ruby
sample :loop_amen, rate: (sample_duration :loop_amen) / (8 / current_bpm * 60)
sleep 8
```

**Comment by isaac-dunn** [comment]
You're right, fractions is what we want. It is true that typically beats are split into powers of two, but it'd be nice to able to split beats in three as well, although I suppose that's a pretty low priority feature.

What are you suggesting then, that we just use 1/8 as the increment?

**Comment by tjvr** [comment]
Yes, I'm suggesting a step size of an eighth. In addition to displaying as fractions, disallowing sleep 0, and automatically syncing samples to the tempo... ;)

**Comment by isaac-dunn** [comment]
Cool. Obviously disallowing `sleep 0` is a good idea, and I agree that for some samples that's a good idea. However, we wouldn't want to change the rate of, for example, a sample of a drum being hit.

**Comment by tjvr** [comment]
Right. I meant just the loop samples. I forgot to say that part.

**Comment by LauraneS** [comment]
Sleep 0 disabled by #27 
& sleep increment steps changed
